[package]
name = "kz_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"
pixels = "0.9.0"
raqote = "0.7.14"
winit = "0.26.1"
font-kit = "0.5.0"
